### ISSUE TITLE
Equipment does not like packs.

### ISSUE THREAD

**Issue by MythicalRollers** [HeroCreationLab/hero-creation-tool#148]
Hello, Sage again with another bug!  Tired of me yet?
When selecting a pack via the builder I get this error.
![image](https://github.com/HeroCreationLab/hero-creation-tool/assets/106455111/2bfb26b5-7927-4741-84cb-9c48802a118f)
8equipmentStep.ts:398 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'system')
[Detected 1 package: hero-creation-tool]
    at _Equipment.makeItemOption (equipmentStep.ts:398:19)
    at _Equipment.addPackToSelection (equipmentStep.ts:254:27)
    at _Equipment.addItemOrPack (equipmentStep.ts:138:12)
    at _Equipment.select (equipmentStep.ts:126:10)
    at HTMLDivElement.<anonymous> (equipmentStep.ts:117:16)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by MythicalRollers** [comment]
Now I do use the module "Item Containers" which is probably a factor here.  As that pack has all the items it comes with "in" it.  So maybe this is less of a bug and more of an enhancement.  Please play nice with "Item Containers".
